# curl -X 'POST'
#  'http://vkedu-fullstack-div2.ru/api/register/'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -H 'X-CSRFToken: BWl5SzaXZ3DHSVla8mr6LX000ZfPbvRDL3fvnCRHrFiKXH5YIPynM6QuUjX70k3m'
#  -d '{
#  "username": "user101",
#  "password": "password",
#  "first_name": "string",
#  "last_name": "string",
#  "bio": "string"
#}'
POST http://vkedu-fullstack-div2.ru/api/register/
accept: application/json
X-CSRFToken: BWl5SzaXZ3DHSVla8mr6LX000ZfPbvRDL3fvnCRHrFiKXH5YIPynM6QuUjX70k3m
Content-Type: application/json

{
  "username": "user101",
  "password": "user101password",
  "first_name": "string",
  "last_name": "string",
  "bio": "string"
}

###

