# curl -X 'POST'
#  'http://vkedu-fullstack-div2.ru/api/auth/'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -H 'X-CSRFToken: UN2L4mCEkDoGRuvKwnyYWnGy5yotVBY42mfHGxlGEsrQ5telSeJ4LE4sfJpaIDUq'
#  -d '{
#  "username": "string",
#  "password": "string"
#}'
POST http://vkedu-fullstack-div2.ru/api/auth/
accept: application/json
Content-Type: application/json

{
  "username": "user101",
  "password": "user101password"
}

###

